### PR TITLE
Allow configurable arguments to requests.Response.json()

### PR DESCRIPTION
**Pull request by elyobo**
As with #8, this is mainly to support control over the handling of
floats; by default requests.Response.json() will parse JSON floats into
python floats, which introduces inaccuracy.

Response.json() just passes the **kwargs on to json.loads() and likewise
this change allows a dict of keywords to be set on the client.

The default behaviour is unchanged.

### CODE REVIEW

**Comment by elyobo** [comment]
@toloco I've updated with your suggested fix for the mutable argument, thanks for the pointer.

**Comment by toloco** [comment]
It's broken for python 3x

* requests-mock should be added in requirements.txt

**Comment by toloco** [comment]
There is a conflict, Ill checkout at home and create a newer version in pypi (0.7)

**Comment by elyobo** [comment]
Yeah, most likely three changes in account creation #13 conflict. I'll
rebase and update the PR if I get a change.

**Comment by toloco** [comment]
thanks mate!
You make a good job!

**Comment by elyobo** [comment]
Yeah, that was the problem.  Rebased and pushed again without conflicts.

**Pull request merged**
