### PR TITLE
  Support Transactions API

### PR DESCRIPTION
**Pull request by elyobo**

### CODE REVIEW

**Comment by elyobo** [comment]
@toloco Note that some changes were made to reduce the duplication in __call and __call_stream by using a third method, __call_raw, to handle the common parts and return the response.  Access to the response was required by the implementation of the request_transaction_history method, as it needs to access the response headers not the response body, but it seemed like a cleaner design anyway.

**Comment by elyobo** [comment]
Resolved merge conflicts resulting from updates to master.

**Comment by toloco** [comment]
Can you make this against develop branch instead? I can't do it myself...

**Comment by elyobo** [comment]
Replaced by PR #22

**Pull request closed without merging**
