### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by elyobo**
Adds integration tests which run against the live Oanda API using the sandbox.

### CODE REVIEW

**Comment by elyobo** [comment]
@toloco This is another one more to see what you think; it probably can't be merged without merging the other various PRs first anyway.  The main idea is to have a set of integration tests as well to ensure that we're up to date with the real API, as well as unit tests where the API is mocked out.  Having the sandbox available makes this feasible, as we can spin up new accounts as needed.

**Comment by elyobo** [comment]
The downside is that these tests show some issues with the Oanda API itself, I think.  It's not totally reliable (the Travis CI build on this failed on one Python 3 version due to such a random failure) and I've had to skip two tests (close trade and close position) because I can only get the API to return HTTP 500s for those tests.

**Comment by toloco** [comment]
Please check travis fail https://travis-ci.org/toloco/pyoanda/builds/73879080

**Comment by elyobo** [comment]
Yeah, like I mentioned above, the Oanda API itself is unreliable - that's an HTTP 500 from Oanda on a valid request (as far as I can tell).  Not sure how to deal with this in the integration tests.

**Comment by toloco** [comment]
Can you make this against develop branch instead? I can't do it myself...

**Comment by elyobo** [comment]
Ha, [apparently I can't](https://github.com/isaacs/github/issues/18), so I'll close this and open another against the develop branch.  I don't think it's ready to merge though, I'm not sure what to do about the inconsistent API responses from Oanda.  I've already marked two of the tests to be skipped (that reliably generate HTTP 500s from Oanda - closing a position and a trade both reliably fail for me).

I think that generally there's value in integration tests, but if the API itself is unreliable... I'm not sure how to accommodate that, as it will break our tests reasonably often if we do merge this in.

**Comment by toloco** [comment]
Please do the pull request against develop branch, Ill merge it

**Comment by elyobo** [comment]
Still not quite ready to merge anyway @toloco, but I did notice something interesting today.  These failing tests (including close_position and close_trade tests which I skip because they always HTTP 500 in the sandbox) work fine in the practice environment, but fail in the development environment.

I could split this in to two sets of tests, one which is minimal and only tests the account management stuff (which is only operational in the sandbox anyway) and one which uses a hard coded set of credentials for a throw away practice account to test all the rest, then we'd have reasonably reliable integration tests.

**Comment by toloco** [comment]
Probably the better is make two different set of test, the current unittest, that it's fine, and then a set of the integration by running an other command, so we wont brake the unittest as we can't rely in a external service.

The integration tests will be optional in CI and setup, so a fail on this won't stop CI neither setup.

What do you think?

**Comment by toloco** [comment]
I move this to dev, dont worry, we have time to properly make this more stable ;)

**Pull request closed without merging**
